# Generated by Django 4.2.21 on 2025-05-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('directors', models.TextField()),
                ('cast', models.TextField()),
                ('plot_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-release_year', 'title'],
                'indexes': [models.Index(fields=['title'], name='movies_movi_title_652549_idx'), models.Index(fields=['release_year'], name='movies_movi_release_81d5c9_idx'), models.Index(fields=['imdb_rating'], name='movies_movi_imdb_ra_8e4972_idx')],
            },
        ),
    ]
