# Generated by Django 4.2.21 on 2025-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_cast_alter_movie_directors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
